// <auto-generated />
using System;
using EmotePurge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmotePurge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801120155_AddVoteSessionHideResultsUntilEnd")]
    partial class AddVoteSessionHideResultsUntilEnd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmotePurge.Core.Entities.AuditLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorLogin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActorTwitchUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .IsDescending();

                    b.HasIndex("ChannelName", "OccurredAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActiveEmoteSetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBotActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TwitchChannelId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName")
                        .IsUnique();

                    b.HasIndex("TwitchChannelId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SevenTvEmoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "SevenTvEmoteId")
                        .IsUnique();

                    b.ToTable("Emotes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.UsageStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("EmoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmoteId", "Date")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("EmoteId", "Date"), new[] { "UseCount" });

                    b.ToTable("UsageStats");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SessionsValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitchAccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TwitchAccessTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitchRefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("TwitchTokenScopes")
                        .HasColumnType("text");

                    b.Property<string>("TwitchUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Vote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EmoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("VoteSessionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoteSessionId", "EmoteId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.VoteSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AllowedVoterRoles")
                        .HasColumnType("integer");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HideResultsUntilEnd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "IsActive");

                    b.ToTable("VoteSessions");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.VoteSessionEmote", b =>
                {
                    b.Property<long>("VoteSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmoteId")
                        .HasColumnType("text");

                    b.HasKey("VoteSessionId", "EmoteId");

                    b.HasIndex("EmoteId");

                    b.ToTable("VoteSessionEmotes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Channel", "Channel")
                        .WithMany("Emotes")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.UsageStat", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Emote", "Emote")
                        .WithMany("UsageStats")
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emote");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Vote", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Emote", "Emote")
                        .WithMany()
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmotePurge.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmotePurge.Core.Entities.VoteSession", "VoteSession")
                        .WithMany("Votes")
                        .HasForeignKey("VoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emote");

                    b.Navigation("User");

                    b.Navigation("VoteSession");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.VoteSession", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.VoteSessionEmote", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Emote", "Emote")
                        .WithMany()
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmotePurge.Core.Entities.VoteSession", "VoteSession")
                        .WithMany("SessionEmotes")
                        .HasForeignKey("VoteSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emote");

                    b.Navigation("VoteSession");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Channel", b =>
                {
                    b.Navigation("Emotes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.Navigation("UsageStats");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.VoteSession", b =>
                {
                    b.Navigation("SessionEmotes");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
