// <auto-generated />
using System;
using EmotePurge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmotePurge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmotePurge.Core.Entities.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ActiveEmoteSetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBotActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TwitchChannelId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName")
                        .IsUnique();

                    b.HasIndex("TwitchChannelId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SevenTvEmoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "SevenTvEmoteId")
                        .IsUnique();

                    b.ToTable("Emotes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.UsageStat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmoteId", "Date")
                        .IsUnique();

                    b.ToTable("UsageStats");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Channel", "Channel")
                        .WithMany("Emotes")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.UsageStat", b =>
                {
                    b.HasOne("EmotePurge.Core.Entities.Emote", "Emote")
                        .WithMany("UsageStats")
                        .HasForeignKey("EmoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emote");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Channel", b =>
                {
                    b.Navigation("Emotes");
                });

            modelBuilder.Entity("EmotePurge.Core.Entities.Emote", b =>
                {
                    b.Navigation("UsageStats");
                });
#pragma warning restore 612, 618
        }
    }
}
